export const SuccessCode = {
  USER_CREATED: "USER_CREATED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",
  USER_LOGGED_OUT_ALL: "USER_LOGGED_OUT_ALL",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  SESSION_LOGGED_OUT: "SESSION_LOGGED_OUT",
  SESSION_LOGGED_OUT_ALL: "SESSION_LOGGED_OUT_ALL",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
} as const;

export type SuccessCodeType = (typeof SuccessCode)[keyof typeof SuccessCode];